# Generated by Django 3.1.4 on 2020-12-21 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='position',
            field=models.CharField(choices=[('Менеджер', 'Менеджер'), ('Секретарь', 'Секретарь'), ('Продавец', 'Продавец'), ('Работник цеха', 'Работник цеха')], max_length=120, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='salary_type',
            field=models.CharField(choices=[('Фиксированная заработная плата', 'Фиксированная заработная плата'), ('Заработная плата + комиссионные', 'Заработная плата + комиссионные'), ('Почасовой оклад', 'Почасовой оклад')], max_length=120, verbose_name='Вид заработной платы'),
        ),
    ]
