# Generated by Django 3.1.4 on 2020-12-21 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_auto_20201221_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='worked_hours',
            field=models.IntegerField(default=1, verbose_name='Отработано часов в неделю'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='worker',
            name='position',
            field=models.CharField(choices=[('Менеджер', 'Менеджер'), ('Секретарь', 'Секретарь'), ('Секретарь на замену', 'Секретарь на замену'), ('Продавец', 'Продавец'), ('Работник цеха', 'Работник цеха')], max_length=120, verbose_name='Должность'),
        ),
    ]
