# Generated by Django 3.1.4 on 2020-12-21 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0003_auto_20201221_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='salary',
            field=models.IntegerField(default=1, verbose_name='Заработная плата'),
            preserve_default=False,
        ),
    ]
