# Generated by Django 3.1.4 on 2020-12-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0005_worker_count_of_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='salary',
            field=models.IntegerField(blank=True, null=True, verbose_name='Заработная плата'),
        ),
    ]
