# Generated by Django 3.1.4 on 2020-12-21 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0006_auto_20201221_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='hour_payment',
            field=models.IntegerField(blank=True, null=True, verbose_name='Оплата за час в сомах'),
        ),
    ]
